### ISSUE TITLE
Elastic search error when running zeebe

### ISSUE THREAD

**Issue by michelefa1988** [camunda-community-hub/zeebe-cluster-helm#114]
When installing the helm chart with in build elastic search (using default settings), I get the following error

Does anyone know what could be causing this? Such an error is thrown by both`eebe-operate` and `zeebe-cluster-helm`, running docker image 1.0.0

`      at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://elasticsearch-master:9200], URI [/_component_template/zeebe-record], status line [HTTP/1.1 405 Method Not Allowed]
{"error":"Incorrect HTTP method for uri [/_component_template/zeebe-record] and method [PUT], allowed: [POST]","status":405}
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:258) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        ... 14 more
2021-06-16 09:43:52.630 [Broker-0-Exporter-2] [Broker-0-zb-fs-workers-0] WARN 
      io.camunda.zeebe.broker.exporter.elasticsearch - Error on exporting record with key 4503599627370497
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to put component template
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:263) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:217) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createComponentTemplate(ElasticsearchExporter.java:183) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createIndexTemplates(ElasticsearchExporter.java:133) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:80) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:151) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:138) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:425) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://elasticsearch-master:9200], URI [/_component_template/zeebe-record], status line [HTTP/1.1 405 Method Not Allowed]
{"error":"Incorrect HTTP method for uri [/_component_template/zeebe-record] and method [PUT], allowed: [POST]","status":405}
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:258) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        ... 14 more
2021-06-16 09:44:02.635 [Broker-0-Exporter-2] [Broker-0-zb-fs-workers-0] WARN 
      io.camunda.zeebe.broker.exporter.elasticsearch - Error on exporting record with key 4503599627370497
io.camunda.zeebe.exporter.ElasticsearchExporterException: Failed to put component template
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:263) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:217) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createComponentTemplate(ElasticsearchExporter.java:183) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.createIndexTemplates(ElasticsearchExporter.java:133) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.exporter.ElasticsearchExporter.export(ElasticsearchExporter.java:80) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.export(ExporterContainer.java:151) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterContainer.exportRecord(ExporterContainer.java:138) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.broker.exporter.stream.ExporterDirector$RecordExporter.export(ExporterDirector.java:425) ~[zeebe-broker-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.retry.BackOffRetryStrategy.run(BackOffRetryStrategy.java:51) ~[zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.invoke(ActorJob.java:76) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorJob.execute(ActorJob.java:39) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorTask.execute(ActorTask.java:122) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.executeCurrentTask(ActorThread.java:94) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.doWork(ActorThread.java:78) [zeebe-util-1.0.0.jar:1.0.0]
        at io.camunda.zeebe.util.sched.ActorThread.run(ActorThread.java:191) [zeebe-util-1.0.0.jar:1.0.0]
Caused by: org.elasticsearch.client.ResponseException: method [PUT], host [http://elasticsearch-master:9200], URI [/_component_template/zeebe-record], status line [HTTP/1.1 405 Method Not Allowed]
{"error":"Incorrect HTTP method for uri [/_component_template/zeebe-record] and method [PUT], allowed: [POST]","status":405}
        at org.elasticsearch.client.RestClient.convertResponse(RestClient.java:326) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:296) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:270) ~[elasticsearch-rest-client-7.12.1.jar:7.12.1]
        at io.camunda.zeebe.exporter.ElasticsearchClient.putComponentTemplate(ElasticsearchClient.java:258) ~[zeebe-elasticsearch-exporter-1.0.0.jar:1.0.0]
`

**Comment by michelefa1988** [comment]
Any updates on this?

**Comment by michelefa1988** [comment]
I can confirm that updating elastic search setting does fix the issue

`
elasticsearch:
  imageTag: 7.10.1`
